[package]
name = "rota_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-rt = "2.6.0"
serde_json = "1.0.78"
serde = "1.0.136"
postgres = "0.19.2"
lazy_static = "1.4.0"
log = "0.4.14"
chrono = "0.4"